name: Publish

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install additional tools
      run: sudo apt install nuget
    - name: Check version
      run: .github/scripts/check-nuget-version.sh csharp/Vim.BFast.csproj Vim.BFast
      shell: bash

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Pack NuGet package
      run: dotnet pack --no-build --include-symbols -p:SymbolPackageFormat=snupkg -c Release csharp/Vim.BFast.csproj -o .
    - name: Push NuGet package
      run: dotnet nuget push Vim.BFast*.nupkg -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json
    - name: Tag commit
      run: .github/scripts/tag-commit.sh csharp/Vim.BFast.csproj
